name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Testes (caso tenha projeto de testes)
      run: dotnet test --no-build --verbosity normal

    - name: Publicar artefato
      run: dotnet publish -c Release -o ./publish

    - name: Upload do artefato
      uses: actions/upload-artifact@v4
      with:
        name: publish
        path: ./publish
